import { Court } from '@/types/application'

interface CourtEntry {
  prefecture: string
  areas: string[] // 管轄する市区町村・郡（前方一致マッチに使用）
  name: string
  address: string
  stampAmount: number // 予納郵便切手代（参考値・要確認）
}

/**
 * 全国簡易裁判所データ
 * ※ 予納郵便切手代は参考値です。申立前に各裁判所へご確認ください。
 * ※ データは最高裁判所ウェブサイト（https://www.courts.go.jp）を参照し、2026年5月に再構築しました。
 * ※ 大阪府は WebSearch により courts.go.jp の実在URLを確認済み（2026-05-07）
 */
const courtData: CourtEntry[] = [
  // ========== 北海道 ==========
  {
    prefecture: '北海道',
    areas: ["札幌市", "石狩市", "北広島市", "江別市", "恵庭市", "千歳市", "当別町", "新篠津村"],
    name: "札幌簡易裁判所",
    address: "北海道札幌市中央区大通西11丁目",
    stampAmount: 6000,
  },
  {
    prefecture: '北海道',
    areas: ["函館市", "北斗市", "亀田郡七飯町", "上磯郡木古内町", "松前郡", "檜山郡"],
    name: "函館簡易裁判所",
    address: "北海道函館市新川町25-18",
    stampAmount: 4000,
  },
  {
    prefecture: '北海道',
    areas: ["小樽市", "余市郡", "積丹郡", "古宇郡", "岩内郡"],
    name: "小樽簡易裁判所",
    address: "北海道小樽市色内1丁目2-1",
    stampAmount: 4000,
  },
  {
    prefecture: '北海道',
    areas: ["旭川市", "上川郡東川町", "上川郡東神楽町", "上川郡当麻町", "上川郡愛別町", "上川郡比布町", "上川郡鷹栖町"],
    name: "旭川簡易裁判所",
    address: "北海道旭川市花咲町4丁目",
    stampAmount: 6000,
  },
  {
    prefecture: '北海道',
    areas: ["室蘭市", "登別市", "白老郡"],
    name: "室蘭簡易裁判所",
    address: "北海道室蘭市入江町1-13",
    stampAmount: 4000,
  },
  {
    prefecture: '北海道',
    areas: ["伊達市", "有珠郡壮瞥町", "虻田郡洞爺湖町"],
    name: "伊達簡易裁判所",
    address: "北海道伊達市鹿島町57-20",
    stampAmount: 4000,
  },
  {
    prefecture: '北海道',
    areas: ["釧路市", "釧路郡釧路町", "白糠郡白糠町", "阿寒郡"],
    name: "釧路簡易裁判所",
    address: "北海道釧路市大町1-1-1",
    stampAmount: 4000,
  },
  {
    prefecture: '北海道',
    areas: ["根室市", "野付郡別海町", "標津郡", "目梨郡"],
    name: "根室簡易裁判所",
    address: "北海道根室市常盤町2-27",
    stampAmount: 3000,
  },
  {
    prefecture: '北海道',
    areas: ["帯広市", "河東郡", "河西郡", "中川郡池田町", "中川郡本別町", "足寄郡", "広尾郡", "十勝郡"],
    name: "帯広簡易裁判所",
    address: "北海道帯広市東1条南11丁目1",
    stampAmount: 4000,
  },
  {
    prefecture: '北海道',
    areas: ["北見市", "常呂郡", "紋別郡佐呂間町"],
    name: "北見簡易裁判所",
    address: "北海道北見市大通西3丁目1-1",
    stampAmount: 4000,
  },
  {
    prefecture: '北海道',
    areas: ["網走市", "斜里郡", "網走郡"],
    name: "網走簡易裁判所",
    address: "北海道網走市南3条東1丁目1",
    stampAmount: 3000,
  },
  {
    prefecture: '北海道',
    areas: ["紋別市", "紋別郡西興部村", "紋別郡雄武町"],
    name: "紋別簡易裁判所",
    address: "北海道紋別市幸町3丁目1-33",
    stampAmount: 3000,
  },
  {
    prefecture: '北海道',
    areas: ["紋別郡遠軽町", "紋別郡滝上町", "紋別郡興部町"],
    name: "遠軽簡易裁判所",
    address: "北海道紋別郡遠軽町大通北1丁目1-1",
    stampAmount: 3000,
  },
  {
    prefecture: '北海道',
    areas: ["網走郡美幌町", "網走郡津別町", "川上郡標茶町", "川上郡弟子屈町"],
    name: "美幌簡易裁判所",
    address: "北海道網走郡美幌町東1条南1丁目",
    stampAmount: 3000,
  },
  {
    prefecture: '北海道',
    areas: ["岩見沢市", "空知郡南幌町", "夕張郡栗山町", "夕張郡長沼町"],
    name: "岩見沢簡易裁判所",
    address: "北海道岩見沢市9条西4丁目",
    stampAmount: 4000,
  },
  {
    prefecture: '北海道',
    areas: ["夕張市", "夕張郡由仁町"],
    name: "夕張簡易裁判所",
    address: "北海道夕張市本町3丁目",
    stampAmount: 3000,
  },
  {
    prefecture: '北海道',
    areas: ["滝川市", "砂川市", "歌志内市", "赤平市", "空知郡奈井江町", "空知郡上砂川町"],
    name: "滝川簡易裁判所",
    address: "北海道滝川市東町2丁目1-42",
    stampAmount: 4000,
  },
  {
    prefecture: '北海道',
    areas: ["深川市", "雨竜郡", "空知郡雨竜町", "空知郡北竜町", "空知郡幌加内町"],
    name: "深川簡易裁判所",
    address: "北海道深川市2条17番地",
    stampAmount: 3000,
  },
  {
    prefecture: '北海道',
    areas: ["富良野市", "空知郡上富良野町", "空知郡中富良野町", "空知郡南富良野町", "勇払郡占冠村"],
    name: "富良野簡易裁判所",
    address: "北海道富良野市日の出町1-30",
    stampAmount: 3000,
  },
  {
    prefecture: '北海道',
    areas: ["苫小牧市", "勇払郡厚真町", "勇払郡むかわ町", "沙流郡日高町"],
    name: "苫小牧簡易裁判所",
    address: "北海道苫小牧市旭町3丁目1-25",
    stampAmount: 4000,
  },
  {
    prefecture: '北海道',
    areas: ["稚内市", "天塩郡", "宗谷郡", "枝幸郡", "礼文郡", "利尻郡"],
    name: "稚内簡易裁判所",
    address: "北海道稚内市大黒2丁目9-3",
    stampAmount: 3000,
  },
  {
    prefecture: '北海道',
    areas: ["留萌市", "苫前郡", "増毛郡", "天塩郡幌延町", "天塩郡豊富町"],
    name: "留萌簡易裁判所",
    address: "北海道留萌市住之江町2丁目1-2",
    stampAmount: 3000,
  },
  {
    prefecture: '北海道',
    areas: ["名寄市", "士別市", "上川郡和寒町", "上川郡剣淵町", "上川郡下川町", "中川郡音威子府村", "中川郡中川町"],
    name: "名寄簡易裁判所",
    address: "北海道名寄市西4条南9丁目1",
    stampAmount: 3000,
  },
  {
    prefecture: '北海道',
    areas: ["浦河郡浦河町", "様似郡", "幌泉郡", "日高郡新ひだか町"],
    name: "浦河簡易裁判所",
    address: "北海道浦河郡浦河町築地1丁目3-1",
    stampAmount: 3000,
  },
  {
    prefecture: '北海道',
    areas: ["虻田郡倶知安町", "磯谷郡蘭越町", "岩内郡共和町", "古宇郡泊村", "古宇郡神恵内村", "虻田郡ニセコ町", "虻田郡真狩村", "虻田郡留寿都村", "虻田郡喜茂別町", "虻田郡京極町"],
    name: "倶知安簡易裁判所",
    address: "北海道虻田郡倶知安町北1条東3丁目",
    stampAmount: 3000,
  },
  {
    prefecture: '北海道',
    areas: ["桧山郡江差町", "爾志郡乙部町", "奥尻郡奥尻島", "今金町", "せたな町"],
    name: "江差簡易裁判所",
    address: "北海道桧山郡江差町字中歌町193",
    stampAmount: 3000,
  },
  {
    prefecture: '北海道',
    areas: ["標津郡中標津町", "標津郡標津町", "目梨郡羅臼町"],
    name: "中標津簡易裁判所",
    address: "北海道標津郡中標津町東5条南1丁目",
    stampAmount: 3000,
  },
  // ========== 青森県 ==========
  {
    prefecture: '青森県',
    areas: ["青森市", "東津軽郡"],
    name: "青森簡易裁判所",
    address: "青森県青森市長島1丁目3-1",
    stampAmount: 4000,
  },
  {
    prefecture: '青森県',
    areas: ["弘前市", "中津軽郡", "南津軽郡大鰐町", "南津軽郡田舎館村", "西津軽郡鰺ヶ沢町", "西津軽郡深浦町"],
    name: "弘前簡易裁判所",
    address: "青森県弘前市大字富田町2-1",
    stampAmount: 4000,
  },
  {
    prefecture: '青森県',
    areas: ["八戸市", "三戸郡", "上北郡おいらせ町"],
    name: "八戸簡易裁判所",
    address: "青森県八戸市廿三日町2",
    stampAmount: 4000,
  },
  {
    prefecture: '青森県',
    areas: ["むつ市", "下北郡", "上北郡野辺地町", "上北郡横浜町"],
    name: "むつ簡易裁判所",
    address: "青森県むつ市小川町2-6-1",
    stampAmount: 3000,
  },
  {
    prefecture: '青森県',
    areas: ["十和田市", "三沢市", "上北郡七戸町", "上北郡六戸町", "上北郡東北町", "上北郡六ヶ所村"],
    name: "十和田簡易裁判所",
    address: "青森県十和田市西二番町6-28",
    stampAmount: 3000,
  },
  {
    prefecture: '青森県',
    areas: ["五所川原市", "北津軽郡", "つがる市", "西津軽郡木造町"],
    name: "五所川原簡易裁判所",
    address: "青森県五所川原市布屋町27-1",
    stampAmount: 3000,
  },
  {
    prefecture: '青森県',
    areas: ["黒石市", "平川市", "南津軽郡田舎館村"],
    name: "黒石簡易裁判所",
    address: "青森県黒石市住吉町11",
    stampAmount: 3000,
  },
  // ========== 岩手県 ==========
  {
    prefecture: '岩手県',
    areas: ["盛岡市", "岩手郡", "滝沢市", "紫波郡"],
    name: "盛岡簡易裁判所",
    address: "岩手県盛岡市内丸9-1",
    stampAmount: 4000,
  },
  {
    prefecture: '岩手県',
    areas: ["花巻市", "遠野市"],
    name: "花巻簡易裁判所",
    address: "岩手県花巻市材木町5-1",
    stampAmount: 3000,
  },
  {
    prefecture: '岩手県',
    areas: ["北上市", "和賀郡"],
    name: "北上簡易裁判所",
    address: "岩手県北上市大通り1丁目3-1",
    stampAmount: 3000,
  },
  {
    prefecture: '岩手県',
    areas: ["奥州市", "胆沢郡金ケ崎町"],
    name: "水沢簡易裁判所",
    address: "岩手県奥州市水沢大手町3-8",
    stampAmount: 3000,
  },
  {
    prefecture: '岩手県',
    areas: ["一関市", "西磐井郡平泉町"],
    name: "一関簡易裁判所",
    address: "岩手県一関市地主町3-48",
    stampAmount: 3000,
  },
  {
    prefecture: '岩手県',
    areas: ["大船渡市", "陸前高田市", "気仙郡"],
    name: "大船渡簡易裁判所",
    address: "岩手県大船渡市大船渡町字台3-5",
    stampAmount: 3000,
  },
  {
    prefecture: '岩手県',
    areas: ["宮古市", "下閉伊郡"],
    name: "宮古簡易裁判所",
    address: "岩手県宮古市宮町1丁目1-10",
    stampAmount: 3000,
  },
  {
    prefecture: '岩手県',
    areas: ["二戸市", "二戸郡", "九戸郡"],
    name: "二戸簡易裁判所",
    address: "岩手県二戸市福岡字川又47",
    stampAmount: 3000,
  },
  {
    prefecture: '岩手県',
    areas: ["久慈市", "九戸郡洋野町", "九戸郡野田村", "九戸郡普代村"],
    name: "久慈簡易裁判所",
    address: "岩手県久慈市川崎町3-3",
    stampAmount: 3000,
  },
  // ========== 宮城県 ==========
  {
    prefecture: '宮城県',
    areas: ["仙台市", "富谷市", "黒川郡", "宮城郡"],
    name: "仙台簡易裁判所",
    address: "宮城県仙台市青葉区片平1丁目6-1",
    stampAmount: 6000,
  },
  {
    prefecture: '宮城県',
    areas: ["白石市", "柴田郡大河原町", "柴田郡村田町", "柴田郡柴田町", "柴田郡川崎町", "刈田郡蔵王町", "刈田郡七ヶ宿町"],
    name: "大河原簡易裁判所",
    address: "宮城県柴田郡大河原町字新南1-4",
    stampAmount: 3000,
  },
  {
    prefecture: '宮城県',
    areas: ["大崎市", "加美郡", "遠田郡"],
    name: "古川簡易裁判所",
    address: "宮城県大崎市古川旭5丁目7-1",
    stampAmount: 3000,
  },
  {
    prefecture: '宮城県',
    areas: ["石巻市", "東松島市", "牡鹿郡", "登米市", "本吉郡南三陸町"],
    name: "石巻簡易裁判所",
    address: "宮城県石巻市穀町14-4",
    stampAmount: 3000,
  },
  {
    prefecture: '宮城県',
    areas: ["気仙沼市", "本吉郡登米町"],
    name: "気仙沼簡易裁判所",
    address: "宮城県気仙沼市八日町1丁目4-8",
    stampAmount: 3000,
  },
  // ========== 秋田県 ==========
  {
    prefecture: '秋田県',
    areas: ["秋田市", "男鹿市", "潟上市", "南秋田郡", "河辺郡"],
    name: "秋田簡易裁判所",
    address: "秋田県秋田市山王7丁目1-1",
    stampAmount: 4000,
  },
  {
    prefecture: '秋田県',
    areas: ["大仙市", "仙北市", "仙北郡"],
    name: "大曲簡易裁判所",
    address: "秋田県大仙市大曲通町5-43",
    stampAmount: 3000,
  },
  {
    prefecture: '秋田県',
    areas: ["横手市", "平鹿郡"],
    name: "横手簡易裁判所",
    address: "秋田県横手市中央町8-2",
    stampAmount: 3000,
  },
  {
    prefecture: '秋田県',
    areas: ["能代市", "山本郡"],
    name: "能代簡易裁判所",
    address: "秋田県能代市末広町4-7",
    stampAmount: 3000,
  },
  {
    prefecture: '秋田県',
    areas: ["大館市", "北秋田市", "北秋田郡"],
    name: "大館簡易裁判所",
    address: "秋田県大館市中城43-1",
    stampAmount: 3000,
  },
  {
    prefecture: '秋田県',
    areas: ["鹿角市", "鹿角郡"],
    name: "鹿角簡易裁判所",
    address: "秋田県鹿角市花輪字荒田38-1",
    stampAmount: 3000,
  },
  {
    prefecture: '秋田県',
    areas: ["由利本荘市", "にかほ市"],
    name: "本荘簡易裁判所",
    address: "秋田県由利本荘市西目町出戸辻ケ沢1-109",
    stampAmount: 3000,
  },
  // ========== 山形県 ==========
  {
    prefecture: '山形県',
    areas: ["山形市", "上山市", "天童市", "東村山郡"],
    name: "山形簡易裁判所",
    address: "山形県山形市旅篭町2丁目3-10",
    stampAmount: 4000,
  },
  {
    prefecture: '山形県',
    areas: ["米沢市", "南陽市", "高畠町", "川西町", "飯豊町", "長井市", "白鷹町"],
    name: "米沢簡易裁判所",
    address: "山形県米沢市金池3丁目1-75",
    stampAmount: 3000,
  },
  {
    prefecture: '山形県',
    areas: ["鶴岡市", "三川町", "庄内町"],
    name: "鶴岡簡易裁判所",
    address: "山形県鶴岡市馬場町13-1",
    stampAmount: 4000,
  },
  {
    prefecture: '山形県',
    areas: ["酒田市", "遊佐町"],
    name: "酒田簡易裁判所",
    address: "山形県酒田市本町2丁目6-1",
    stampAmount: 3000,
  },
  {
    prefecture: '山形県',
    areas: ["新庄市", "最上郡"],
    name: "新庄簡易裁判所",
    address: "山形県新庄市沖の町10-24",
    stampAmount: 3000,
  },
  {
    prefecture: '山形県',
    areas: ["村山市", "尾花沢市", "東根市", "北村山郡"],
    name: "村山簡易裁判所",
    address: "山形県村山市中央1丁目3-6",
    stampAmount: 3000,
  },
  // ========== 福島県 ==========
  {
    prefecture: '福島県',
    areas: ["福島市", "伊達市", "伊達郡", "相馬郡飯館村"],
    name: "福島簡易裁判所",
    address: "福島県福島市霞町1-46",
    stampAmount: 4000,
  },
  {
    prefecture: '福島県',
    areas: ["郡山市", "岩瀬郡"],
    name: "郡山簡易裁判所",
    address: "福島県郡山市麓山1丁目1-1",
    stampAmount: 4000,
  },
  {
    prefecture: '福島県',
    areas: ["いわき市"],
    name: "いわき簡易裁判所",
    address: "福島県いわき市平字梅本21",
    stampAmount: 4000,
  },
  {
    prefecture: '福島県',
    areas: ["会津若松市", "耶麻郡", "河沼郡", "大沼郡", "南会津郡"],
    name: "会津若松簡易裁判所",
    address: "福島県会津若松市追手町2-9",
    stampAmount: 4000,
  },
  {
    prefecture: '福島県',
    areas: ["白河市", "西白河郡"],
    name: "白河簡易裁判所",
    address: "福島県白河市郭内146",
    stampAmount: 3000,
  },
  {
    prefecture: '福島県',
    areas: ["東白川郡棚倉町", "石川郡", "田村郡", "東白川郡"],
    name: "棚倉簡易裁判所",
    address: "福島県東白川郡棚倉町大字棚倉字南町132",
    stampAmount: 3000,
  },
  {
    prefecture: '福島県',
    areas: ["須賀川市", "田村市", "田村郡三春町", "田村郡小野町"],
    name: "須賀川簡易裁判所",
    address: "福島県須賀川市八幡町135",
    stampAmount: 3000,
  },
  {
    prefecture: '福島県',
    areas: ["喜多方市", "耶麻郡西会津町", "耶麻郡磐梯町", "耶麻郡猪苗代町"],
    name: "喜多方簡易裁判所",
    address: "福島県喜多方市1丁目4698",
    stampAmount: 3000,
  },
  {
    prefecture: '福島県',
    areas: ["相馬市", "南相馬市", "双葉郡", "相馬郡"],
    name: "相馬簡易裁判所",
    address: "福島県相馬市中村字北町63",
    stampAmount: 3000,
  },
  // ========== 茨城県 ==========
  {
    prefecture: '茨城県',
    areas: ["水戸市", "ひたちなか市", "那珂市", "那珂郡", "東茨城郡"],
    name: "水戸簡易裁判所",
    address: "茨城県水戸市大町1丁目1-38",
    stampAmount: 4000,
  },
  {
    prefecture: '茨城県',
    areas: ["土浦市", "つくば市", "つくばみらい市", "稲敷市", "牛久市"],
    name: "土浦簡易裁判所",
    address: "茨城県土浦市中央1丁目13-12",
    stampAmount: 4000,
  },
  {
    prefecture: '茨城県',
    areas: ["日立市", "高萩市", "北茨城市", "久慈郡"],
    name: "日立簡易裁判所",
    address: "茨城県日立市助川町1丁目6-1",
    stampAmount: 3000,
  },
  {
    prefecture: '茨城県',
    areas: ["常陸太田市", "常陸大宮市", "久慈郡大子町"],
    name: "常陸太田簡易裁判所",
    address: "茨城県常陸太田市金井町3615",
    stampAmount: 3000,
  },
  {
    prefecture: '茨城県',
    areas: ["龍ケ崎市", "取手市", "守谷市", "北相馬郡", "河内郡"],
    name: "龍ケ崎簡易裁判所",
    address: "茨城県龍ケ崎市3710",
    stampAmount: 3000,
  },
  {
    prefecture: '茨城県',
    areas: ["下妻市", "筑西市", "桜川市", "結城市", "結城郡"],
    name: "下妻簡易裁判所",
    address: "茨城県下妻市下妻乙99",
    stampAmount: 3000,
  },
  {
    prefecture: '茨城県',
    areas: ["行方市", "鉾田市", "潮来市", "神栖市", "鹿嶋市", "鹿行郡"],
    name: "麻生簡易裁判所",
    address: "茨城県行方市麻生143",
    stampAmount: 3000,
  },
  {
    prefecture: '茨城県',
    areas: ["古河市", "坂東市", "五霞町", "猿島郡境町"],
    name: "古河簡易裁判所",
    address: "茨城県古河市本町2丁目2-30",
    stampAmount: 3000,
  },
  // ========== 栃木県 ==========
  {
    prefecture: '栃木県',
    areas: ["宇都宮市", "上三川町", "芳賀郡", "下野市", "河内郡"],
    name: "宇都宮簡易裁判所",
    address: "栃木県宇都宮市小幡2丁目1-11",
    stampAmount: 4000,
  },
  {
    prefecture: '栃木県',
    areas: ["足利市"],
    name: "足利簡易裁判所",
    address: "栃木県足利市伊勢町1丁目1-38",
    stampAmount: 3000,
  },
  {
    prefecture: '栃木県',
    areas: ["栃木市", "小山市", "都賀郡", "下都賀郡"],
    name: "栃木簡易裁判所",
    address: "栃木県栃木市万町15-15",
    stampAmount: 3000,
  },
  {
    prefecture: '栃木県',
    areas: ["日光市"],
    name: "今市簡易裁判所",
    address: "栃木県日光市今市720",
    stampAmount: 3000,
  },
  {
    prefecture: '栃木県',
    areas: ["大田原市", "那須塩原市", "那須郡"],
    name: "大田原簡易裁判所",
    address: "栃木県大田原市中央1丁目3-10",
    stampAmount: 3000,
  },
  {
    prefecture: '栃木県',
    areas: ["矢板市", "塩谷郡", "さくら市"],
    name: "矢板簡易裁判所",
    address: "栃木県矢板市扇町2丁目7-20",
    stampAmount: 3000,
  },
  {
    prefecture: '栃木県',
    areas: ["真岡市", "益子町", "茂木町", "市貝町"],
    name: "真岡簡易裁判所",
    address: "栃木県真岡市荒町5291-1",
    stampAmount: 3000,
  },
  // ========== 群馬県 ==========
  {
    prefecture: '群馬県',
    areas: ["前橋市", "渋川市", "北群馬郡", "勢多郡"],
    name: "前橋簡易裁判所",
    address: "群馬県前橋市大手町3丁目1-1",
    stampAmount: 4000,
  },
  {
    prefecture: '群馬県',
    areas: ["高崎市", "富岡市", "甘楽郡", "吉井町"],
    name: "高崎簡易裁判所",
    address: "群馬県高崎市高松町26-2",
    stampAmount: 4000,
  },
  {
    prefecture: '群馬県',
    areas: ["桐生市", "みどり市", "山田郡"],
    name: "桐生簡易裁判所",
    address: "群馬県桐生市元宿町1-17",
    stampAmount: 3000,
  },
  {
    prefecture: '群馬県',
    areas: ["太田市", "館林市", "邑楽郡"],
    name: "太田簡易裁判所",
    address: "群馬県太田市小舞木町34-1",
    stampAmount: 3000,
  },
  {
    prefecture: '群馬県',
    areas: ["沼田市", "利根郡"],
    name: "沼田簡易裁判所",
    address: "群馬県沼田市栄町1-11",
    stampAmount: 3000,
  },
  {
    prefecture: '群馬県',
    areas: ["中之条町", "吾妻郡"],
    name: "吾妻簡易裁判所",
    address: "群馬県吾妻郡中之条町大字中之条町1092",
    stampAmount: 3000,
  },
  {
    prefecture: '群馬県',
    areas: ["藤岡市", "多野郡"],
    name: "藤岡簡易裁判所",
    address: "群馬県藤岡市藤岡1320",
    stampAmount: 3000,
  },
  // ========== 埼玉県 ==========
  {
    prefecture: '埼玉県',
    areas: ["さいたま市", "上尾市", "桶川市", "北本市", "伊奈町"],
    name: "さいたま簡易裁判所",
    address: "埼玉県さいたま市浦和区高砂3丁目16-45",
    stampAmount: 6000,
  },
  {
    prefecture: '埼玉県',
    areas: ["川口市", "蕨市", "戸田市"],
    name: "川口簡易裁判所",
    address: "埼玉県川口市青木2丁目1-10",
    stampAmount: 4000,
  },
  {
    prefecture: '埼玉県',
    areas: ["熊谷市", "深谷市", "行田市", "鴻巣市", "北埼玉郡"],
    name: "熊谷簡易裁判所",
    address: "埼玉県熊谷市宮町2丁目49",
    stampAmount: 4000,
  },
  {
    prefecture: '埼玉県',
    areas: ["川越市", "坂戸市", "鶴ヶ島市", "日高市", "入間郡"],
    name: "川越簡易裁判所",
    address: "埼玉県川越市宮下町1丁目8-20",
    stampAmount: 4000,
  },
  {
    prefecture: '埼玉県',
    areas: ["春日部市", "越谷市", "草加市", "三郷市", "吉川市", "八潮市", "松伏町"],
    name: "春日部簡易裁判所",
    address: "埼玉県春日部市粕壁6丁目1-8",
    stampAmount: 4000,
  },
  {
    prefecture: '埼玉県',
    areas: ["所沢市", "狭山市", "入間市", "飯能市", "富士見市", "ふじみ野市", "三芳町", "毛呂山町", "越生町"],
    name: "所沢簡易裁判所",
    address: "埼玉県所沢市元町3-14",
    stampAmount: 4000,
  },
  {
    prefecture: '埼玉県',
    areas: ["久喜市", "幸手市", "蓮田市", "白岡市", "宮代町", "杉戸町"],
    name: "久喜簡易裁判所",
    address: "埼玉県久喜市久喜東1丁目1-33",
    stampAmount: 3000,
  },
  {
    prefecture: '埼玉県',
    areas: ["秩父市", "秩父郡"],
    name: "秩父簡易裁判所",
    address: "埼玉県秩父市熊木町8-15",
    stampAmount: 3000,
  },
  // ========== 千葉県 ==========
  {
    prefecture: '千葉県',
    areas: ["千葉市", "市原市", "習志野市", "八千代市", "四街道市", "印西市", "白井市"],
    name: "千葉簡易裁判所",
    address: "千葉県千葉市中央区中央4丁目11-27",
    stampAmount: 6000,
  },
  {
    prefecture: '千葉県',
    areas: ["松戸市", "流山市", "野田市", "柏市", "我孫子市", "鎌ケ谷市"],
    name: "松戸簡易裁判所",
    address: "千葉県松戸市岩瀬無番地",
    stampAmount: 4000,
  },
  {
    prefecture: '千葉県',
    areas: ["佐倉市", "成田市", "富里市", "印旛郡"],
    name: "佐倉簡易裁判所",
    address: "千葉県佐倉市裁判所前",
    stampAmount: 3000,
  },
  {
    prefecture: '千葉県',
    areas: ["木更津市", "君津市", "富津市", "袖ケ浦市", "鴨川市", "南房総市"],
    name: "木更津簡易裁判所",
    address: "千葉県木更津市富士見1丁目8-3",
    stampAmount: 3000,
  },
  {
    prefecture: '千葉県',
    areas: ["銚子市", "旭市", "香取市", "香取郡"],
    name: "銚子簡易裁判所",
    address: "千葉県銚子市栄町2丁目2",
    stampAmount: 3000,
  },
  {
    prefecture: '千葉県',
    areas: ["匝瑳市", "山武市", "山武郡", "大網白里市", "東金市"],
    name: "八日市場簡易裁判所",
    address: "千葉県匝瑳市八日市場イ2760",
    stampAmount: 3000,
  },
  {
    prefecture: '千葉県',
    areas: ["館山市", "南房総市", "安房郡鋸南町"],
    name: "館山簡易裁判所",
    address: "千葉県館山市北条1073",
    stampAmount: 3000,
  },
  {
    prefecture: '千葉県',
    areas: ["いすみ市", "勝浦市", "夷隅郡", "茂原市", "長生郡"],
    name: "夷隅簡易裁判所",
    address: "千葉県いすみ市大原7400",
    stampAmount: 3000,
  },
  // ========== 東京都 ==========
  {
    prefecture: '東京都',
    areas: ["千代田区", "中央区", "港区", "新宿区", "文京区", "台東区", "墨田区", "江東区", "品川区", "目黒区", "大田区", "世田谷区", "渋谷区", "中野区", "杉並区", "豊島区", "北区", "荒川区", "板橋区", "練馬区", "足立区", "葛飾区", "江戸川区"],
    name: "東京簡易裁判所",
    address: "東京都千代田区隼町4-2",
    stampAmount: 6000,
  },
  {
    prefecture: '東京都',
    areas: ["八王子市", "日野市", "多摩市", "稲城市"],
    name: "八王子簡易裁判所",
    address: "東京都八王子市明神町4丁目21-1",
    stampAmount: 4000,
  },
  {
    prefecture: '東京都',
    areas: ["立川市", "昭島市", "国分寺市", "国立市", "府中市", "調布市", "小金井市", "小平市", "東大和市", "武蔵村山市", "西東京市", "東村山市", "清瀬市", "武蔵野市", "三鷹市"],
    name: "立川簡易裁判所",
    address: "東京都立川市緑町10-4",
    stampAmount: 4000,
  },
  {
    prefecture: '東京都',
    areas: ["町田市"],
    name: "町田簡易裁判所",
    address: "東京都町田市森野2丁目2-22",
    stampAmount: 4000,
  },
  {
    prefecture: '東京都',
    areas: ["青梅市", "福生市", "羽村市", "あきる野市", "西多摩郡"],
    name: "青梅簡易裁判所",
    address: "東京都青梅市東青梅2丁目11-22",
    stampAmount: 3000,
  },
  // ========== 神奈川県 ==========
  {
    prefecture: '神奈川県',
    areas: ["横浜市", "横浜市都筑区", "横浜市青葉区", "横浜市緑区", "横浜市港北区", "横浜市旭区", "横浜市保土ケ谷区", "横浜市西区", "横浜市中区", "横浜市南区", "横浜市磯子区", "横浜市金沢区", "横浜市港南区", "横浜市戸塚区", "横浜市瀬谷区", "横浜市泉区", "横浜市栄区"],
    name: "横浜簡易裁判所",
    address: "神奈川県横浜市中区寿町1-2",
    stampAmount: 6000,
  },
  {
    prefecture: '神奈川県',
    areas: ["横浜市神奈川区"],
    name: "神奈川簡易裁判所",
    address: "神奈川県横浜市神奈川区鶴屋町3-32-14",
    stampAmount: 4000,
  },
  {
    prefecture: '神奈川県',
    areas: ["川崎市"],
    name: "川崎簡易裁判所",
    address: "神奈川県川崎市川崎区富士見1丁目1-3",
    stampAmount: 6000,
  },
  {
    prefecture: '神奈川県',
    areas: ["横須賀市", "三浦市", "三浦郡"],
    name: "横須賀簡易裁判所",
    address: "神奈川県横須賀市大滝町2丁目17",
    stampAmount: 4000,
  },
  {
    prefecture: '神奈川県',
    areas: ["小田原市", "南足柄市", "足柄上郡", "足柄下郡"],
    name: "小田原簡易裁判所",
    address: "神奈川県小田原市荻窪350-1",
    stampAmount: 4000,
  },
  {
    prefecture: '神奈川県',
    areas: ["相模原市", "座間市", "綾瀬市", "海老名市", "大和市", "厚木市", "愛甲郡"],
    name: "相模原簡易裁判所",
    address: "神奈川県相模原市中央区富士見6-1-1",
    stampAmount: 4000,
  },
  {
    prefecture: '神奈川県',
    areas: ["平塚市", "藤沢市", "茅ヶ崎市", "秦野市", "伊勢原市", "高座郡", "中郡"],
    name: "平塚簡易裁判所",
    address: "神奈川県平塚市追分1-22",
    stampAmount: 4000,
  },
  // ========== 新潟県 ==========
  {
    prefecture: '新潟県',
    areas: ["新潟市", "阿賀野市", "北蒲原郡", "岩船郡"],
    name: "新潟簡易裁判所",
    address: "新潟県新潟市中央区学校町通1-1",
    stampAmount: 4000,
  },
  {
    prefecture: '新潟県',
    areas: ["三条市", "加茂市", "燕市", "南蒲原郡"],
    name: "三条簡易裁判所",
    address: "新潟県三条市旭町2丁目6-1",
    stampAmount: 3000,
  },
  {
    prefecture: '新潟県',
    areas: ["長岡市", "小千谷市", "出雲崎町"],
    name: "長岡簡易裁判所",
    address: "新潟県長岡市学校町1丁目1-1",
    stampAmount: 4000,
  },
  {
    prefecture: '新潟県',
    areas: ["新発田市", "胎内市", "北蒲原郡聖籠町"],
    name: "新発田簡易裁判所",
    address: "新潟県新発田市大手町3丁目2-1",
    stampAmount: 3000,
  },
  {
    prefecture: '新潟県',
    areas: ["柏崎市", "刈羽郡"],
    name: "柏崎簡易裁判所",
    address: "新潟県柏崎市中央町5-68",
    stampAmount: 3000,
  },
  {
    prefecture: '新潟県',
    areas: ["十日町市", "中魚沼郡", "南魚沼郡"],
    name: "十日町簡易裁判所",
    address: "新潟県十日町市翠町4丁目1",
    stampAmount: 3000,
  },
  {
    prefecture: '新潟県',
    areas: ["佐渡市"],
    name: "佐渡簡易裁判所",
    address: "新潟県佐渡市相川1丁目",
    stampAmount: 3000,
  },
  {
    prefecture: '新潟県',
    areas: ["南魚沼市", "魚沼市"],
    name: "六日町簡易裁判所",
    address: "新潟県南魚沼市六日町4-1",
    stampAmount: 3000,
  },
  // ========== 富山県 ==========
  {
    prefecture: '富山県',
    areas: ["富山市", "中新川郡", "上新川郡"],
    name: "富山簡易裁判所",
    address: "富山県富山市西田地方町2-9-1",
    stampAmount: 4000,
  },
  {
    prefecture: '富山県',
    areas: ["高岡市", "射水市", "氷見市", "砺波市", "小矢部市", "南砺市"],
    name: "高岡簡易裁判所",
    address: "富山県高岡市丸の内1-1",
    stampAmount: 4000,
  },
  {
    prefecture: '富山県',
    areas: ["魚津市", "黒部市", "滑川市", "下新川郡"],
    name: "魚津簡易裁判所",
    address: "富山県魚津市新金屋1丁目12-30",
    stampAmount: 3000,
  },
  // ========== 石川県 ==========
  {
    prefecture: '石川県',
    areas: ["金沢市", "野々市市", "河北郡", "かほく市"],
    name: "金沢簡易裁判所",
    address: "石川県金沢市丸の内7-1",
    stampAmount: 4000,
  },
  {
    prefecture: '石川県',
    areas: ["小松市", "加賀市", "能美市", "川北町"],
    name: "小松簡易裁判所",
    address: "石川県小松市丸の内公園町19",
    stampAmount: 3000,
  },
  {
    prefecture: '石川県',
    areas: ["七尾市", "鹿島郡", "羽咋市", "羽咋郡", "中能登町"],
    name: "七尾簡易裁判所",
    address: "石川県七尾市馬出町ハ部5",
    stampAmount: 3000,
  },
  {
    prefecture: '石川県',
    areas: ["輪島市", "珠洲市", "鳳珠郡"],
    name: "輪島簡易裁判所",
    address: "石川県輪島市河井町20-1-1",
    stampAmount: 3000,
  },
  // ========== 福井県 ==========
  {
    prefecture: '福井県',
    areas: ["福井市", "坂井市", "吉田郡", "丹生郡", "あわら市"],
    name: "福井簡易裁判所",
    address: "福井県福井市春山1丁目1-54",
    stampAmount: 4000,
  },
  {
    prefecture: '福井県',
    areas: ["越前市", "鯖江市", "南条郡", "今立郡", "越前町", "敦賀市"],
    name: "武生簡易裁判所",
    address: "福井県越前市府中1丁目13-10",
    stampAmount: 3000,
  },
  {
    prefecture: '福井県',
    areas: ["小浜市", "大飯郡", "三方郡", "三方上中郡"],
    name: "小浜簡易裁判所",
    address: "福井県小浜市城内1丁目1-13",
    stampAmount: 3000,
  },
  // ========== 山梨県 ==========
  {
    prefecture: '山梨県',
    areas: ["甲府市", "甲斐市", "南アルプス市", "中巨摩郡", "西八代郡市川三郷町", "韮崎市"],
    name: "甲府簡易裁判所",
    address: "山梨県甲府市丸の内1丁目1-18",
    stampAmount: 4000,
  },
  {
    prefecture: '山梨県',
    areas: ["都留市", "大月市", "上野原市", "南都留郡", "北都留郡"],
    name: "都留簡易裁判所",
    address: "山梨県都留市法務局通2-1",
    stampAmount: 3000,
  },
  {
    prefecture: '山梨県',
    areas: ["山梨市", "笛吹市", "甲州市", "東山梨郡", "中央市"],
    name: "山梨簡易裁判所",
    address: "山梨県山梨市上神内川3956",
    stampAmount: 3000,
  },
  // ========== 長野県 ==========
  {
    prefecture: '長野県',
    areas: ["長野市", "須坂市", "千曲市", "埴科郡", "上高井郡", "上水内郡"],
    name: "長野簡易裁判所",
    address: "長野県長野市大字南長野南県町1002-1",
    stampAmount: 4000,
  },
  {
    prefecture: '長野県',
    areas: ["松本市", "塩尻市", "安曇野市", "東筑摩郡", "南安曇郡"],
    name: "松本簡易裁判所",
    address: "長野県松本市丸の内9-1",
    stampAmount: 4000,
  },
  {
    prefecture: '長野県',
    areas: ["上田市", "東御市", "小県郡"],
    name: "上田簡易裁判所",
    address: "長野県上田市材木町1丁目2-6",
    stampAmount: 3000,
  },
  {
    prefecture: '長野県',
    areas: ["飯田市", "下伊那郡"],
    name: "飯田簡易裁判所",
    address: "長野県飯田市追手町2丁目678",
    stampAmount: 3000,
  },
  {
    prefecture: '長野県',
    areas: ["佐久市", "小諸市", "南佐久郡", "北佐久郡", "御代田町", "軽井沢町"],
    name: "佐久簡易裁判所",
    address: "長野県佐久市跡部65-1",
    stampAmount: 3000,
  },
  {
    prefecture: '長野県',
    areas: ["伊那市", "駒ヶ根市", "上伊那郡"],
    name: "伊那簡易裁判所",
    address: "長野県伊那市荒井3022",
    stampAmount: 3000,
  },
  {
    prefecture: '長野県',
    areas: ["大町市", "北安曇郡"],
    name: "大町簡易裁判所",
    address: "長野県大町市大町3621",
    stampAmount: 3000,
  },
  {
    prefecture: '長野県',
    areas: ["諏訪市", "岡谷市", "茅野市", "諏訪郡", "富士見町", "原村"],
    name: "諏訪簡易裁判所",
    address: "長野県諏訪市清水1丁目1643-1",
    stampAmount: 3000,
  },
  {
    prefecture: '長野県',
    areas: ["木曽郡", "木曽町", "上松町", "大桑村", "南木曽町", "木祖村", "王滝村"],
    name: "木曽福島簡易裁判所",
    address: "長野県木曽郡木曽町福島2754-2",
    stampAmount: 3000,
  },
  {
    prefecture: '長野県',
    areas: ["中野市", "飯山市", "下高井郡", "上水内郡信濃町", "下水内郡"],
    name: "中野簡易裁判所",
    address: "長野県中野市中央1丁目2-21",
    stampAmount: 3000,
  },
  // ========== 岐阜県 ==========
  {
    prefecture: '岐阜県',
    areas: ["岐阜市", "羽島市", "羽島郡", "山県市", "瑞穂市", "本巣市", "本巣郡"],
    name: "岐阜簡易裁判所",
    address: "岐阜県岐阜市司町40-1",
    stampAmount: 4000,
  },
  {
    prefecture: '岐阜県',
    areas: ["大垣市", "海津市", "養老郡", "不破郡", "安八郡", "揖斐郡"],
    name: "大垣簡易裁判所",
    address: "岐阜県大垣市丸の内2丁目29",
    stampAmount: 4000,
  },
  {
    prefecture: '岐阜県',
    areas: ["高山市", "飛騨市", "下呂市", "大野郡"],
    name: "高山簡易裁判所",
    address: "岐阜県高山市丸の内町1丁目108",
    stampAmount: 3000,
  },
  {
    prefecture: '岐阜県',
    areas: ["多治見市", "可児市", "可児郡", "土岐市"],
    name: "多治見簡易裁判所",
    address: "岐阜県多治見市音羽町1丁目316-1",
    stampAmount: 3000,
  },
  {
    prefecture: '岐阜県',
    areas: ["中津川市", "恵那市"],
    name: "中津川簡易裁判所",
    address: "岐阜県中津川市山下町2丁目1-2",
    stampAmount: 3000,
  },
  {
    prefecture: '岐阜県',
    areas: ["美濃加茂市", "関市", "美濃市", "郡上市", "加茂郡", "御嵩町"],
    name: "御嵩簡易裁判所",
    address: "岐阜県可児郡御嵩町御嵩1612-2",
    stampAmount: 3000,
  },
  // ========== 静岡県 ==========
  {
    prefecture: '静岡県',
    areas: ["静岡市", "焼津市", "藤枝市", "島田市", "牧之原市", "榛原郡"],
    name: "静岡簡易裁判所",
    address: "静岡県静岡市葵区追手町9-18",
    stampAmount: 4000,
  },
  {
    prefecture: '静岡県',
    areas: ["浜松市", "湖西市", "磐田市", "袋井市"],
    name: "浜松簡易裁判所",
    address: "静岡県浜松市中区利町302-2",
    stampAmount: 4000,
  },
  {
    prefecture: '静岡県',
    areas: ["沼津市", "三島市", "裾野市", "清水町", "長泉町", "函南町", "田方郡", "駿東郡小山町"],
    name: "沼津簡易裁判所",
    address: "静岡県沼津市御幸町15-13",
    stampAmount: 4000,
  },
  {
    prefecture: '静岡県',
    areas: ["掛川市", "菊川市", "御前崎市"],
    name: "掛川簡易裁判所",
    address: "静岡県掛川市長谷1丁目1-1",
    stampAmount: 3000,
  },
  {
    prefecture: '静岡県',
    areas: ["下田市", "賀茂郡", "伊豆市", "伊豆の国市"],
    name: "下田簡易裁判所",
    address: "静岡県下田市二の岡1丁目16-4",
    stampAmount: 3000,
  },
  {
    prefecture: '静岡県',
    areas: ["熱海市", "伊東市"],
    name: "熱海簡易裁判所",
    address: "静岡県熱海市中央町4-3",
    stampAmount: 3000,
  },
  // ========== 愛知県 ==========
  {
    prefecture: '愛知県',
    areas: ["名古屋市", "春日井市", "小牧市", "犬山市", "江南市", "岩倉市", "大口町", "扶桑町", "北名古屋市", "清須市", "あま市", "大治町", "蟹江町", "飛島村"],
    name: "名古屋簡易裁判所",
    address: "愛知県名古屋市中区三の丸1丁目7-1",
    stampAmount: 6000,
  },
  {
    prefecture: '愛知県',
    areas: ["一宮市", "稲沢市", "愛西市", "弥富市"],
    name: "一宮簡易裁判所",
    address: "愛知県一宮市宮町2丁目4-1",
    stampAmount: 4000,
  },
  {
    prefecture: '愛知県',
    areas: ["岡崎市", "安城市", "刈谷市", "知立市", "高浜市", "碧南市", "西尾市", "額田郡幸田町"],
    name: "岡崎簡易裁判所",
    address: "愛知県岡崎市明大寺町字西郷中38",
    stampAmount: 4000,
  },
  {
    prefecture: '愛知県',
    areas: ["豊橋市", "田原市", "豊川市", "蒲郡市", "新城市", "北設楽郡"],
    name: "豊橋簡易裁判所",
    address: "愛知県豊橋市八町通5丁目1",
    stampAmount: 4000,
  },
  {
    prefecture: '愛知県',
    areas: ["豊田市", "みよし市"],
    name: "豊田簡易裁判所",
    address: "愛知県豊田市常盤町2丁目37",
    stampAmount: 4000,
  },
  {
    prefecture: '愛知県',
    areas: ["半田市", "常滑市", "東海市", "大府市", "知多市", "阿久比町", "東浦町", "南知多町", "美浜町", "武豊町"],
    name: "半田簡易裁判所",
    address: "愛知県半田市錦町1丁目11",
    stampAmount: 3000,
  },
  {
    prefecture: '愛知県',
    areas: ["瀬戸市", "尾張旭市", "長久手市", "日進市", "豊明市", "東郷町"],
    name: "瀬戸簡易裁判所",
    address: "愛知県瀬戸市西追分町59-1",
    stampAmount: 3000,
  },
  {
    prefecture: '愛知県',
    areas: ["津島市", "海部郡"],
    name: "津島簡易裁判所",
    address: "愛知県津島市西柳原町1丁目1",
    stampAmount: 3000,
  },
  // ========== 三重県 ==========
  {
    prefecture: '三重県',
    areas: ["津市", "鈴鹿市", "亀山市"],
    name: "津簡易裁判所",
    address: "三重県津市中央3-1",
    stampAmount: 4000,
  },
  {
    prefecture: '三重県',
    areas: ["四日市市", "桑名市", "いなべ市", "員弁郡", "桑名郡", "三重郡", "菰野町"],
    name: "四日市簡易裁判所",
    address: "三重県四日市市諏訪町2-2",
    stampAmount: 4000,
  },
  {
    prefecture: '三重県',
    areas: ["伊勢市", "鳥羽市", "志摩市", "度会郡"],
    name: "伊勢簡易裁判所",
    address: "三重県伊勢市吹上2丁目3-26",
    stampAmount: 3000,
  },
  {
    prefecture: '三重県',
    areas: ["松阪市", "多気郡"],
    name: "松阪簡易裁判所",
    address: "三重県松阪市鎌田町148",
    stampAmount: 3000,
  },
  {
    prefecture: '三重県',
    areas: ["伊賀市", "名張市"],
    name: "伊賀簡易裁判所",
    address: "三重県伊賀市四十九町2802",
    stampAmount: 3000,
  },
  {
    prefecture: '三重県',
    areas: ["熊野市", "南牟婁郡", "北牟婁郡"],
    name: "熊野簡易裁判所",
    address: "三重県熊野市井戸町672",
    stampAmount: 3000,
  },
  {
    prefecture: '三重県',
    areas: ["尾鷲市", "北牟婁郡紀北町"],
    name: "尾鷲簡易裁判所",
    address: "三重県尾鷲市坂場西町1-1",
    stampAmount: 3000,
  },
  // ========== 滋賀県 ==========
  {
    prefecture: '滋賀県',
    areas: ["大津市", "草津市", "守山市", "栗東市", "野洲市", "湖南市"],
    name: "大津簡易裁判所",
    address: "滋賀県大津市京町3丁目1-1",
    stampAmount: 4000,
  },
  {
    prefecture: '滋賀県',
    areas: ["彦根市", "愛知郡愛荘町", "犬上郡"],
    name: "彦根簡易裁判所",
    address: "滋賀県彦根市尾末町1-1",
    stampAmount: 3000,
  },
  {
    prefecture: '滋賀県',
    areas: ["長浜市", "米原市", "坂田郡"],
    name: "長浜簡易裁判所",
    address: "滋賀県長浜市公園町5-20",
    stampAmount: 3000,
  },
  {
    prefecture: '滋賀県',
    areas: ["東近江市", "近江八幡市", "蒲生郡"],
    name: "東近江簡易裁判所",
    address: "滋賀県東近江市八日市緑町20-24",
    stampAmount: 3000,
  },
  {
    prefecture: '滋賀県',
    areas: ["甲賀市"],
    name: "水口簡易裁判所",
    address: "滋賀県甲賀市水口町水口6070",
    stampAmount: 3000,
  },
  // ========== 京都府 ==========
  {
    prefecture: '京都府',
    areas: ["京都市", "乙訓郡", "向日市", "長岡京市"],
    name: "京都簡易裁判所",
    address: "京都府京都市上京区天神北町1-3",
    stampAmount: 6000,
  },
  {
    prefecture: '京都府',
    areas: ["福知山市", "綾部市"],
    name: "福知山簡易裁判所",
    address: "京都府福知山市内記1丁目2-7",
    stampAmount: 3000,
  },
  {
    prefecture: '京都府',
    areas: ["舞鶴市"],
    name: "舞鶴簡易裁判所",
    address: "京都府舞鶴市字南田辺34",
    stampAmount: 3000,
  },
  {
    prefecture: '京都府',
    areas: ["木津川市", "相楽郡", "城陽市", "八幡市", "京田辺市", "久世郡"],
    name: "木津簡易裁判所",
    address: "京都府木津川市木津内田5",
    stampAmount: 3000,
  },
  {
    prefecture: '京都府',
    areas: ["宮津市", "与謝郡", "京丹後市", "伊根町"],
    name: "宮津簡易裁判所",
    address: "京都府宮津市字鶴賀2047",
    stampAmount: 3000,
  },
  // ========== 大阪府 ==========
  {
    prefecture: '大阪府',
    areas: ["大阪市", "守口市", "門真市"],
    name: "大阪簡易裁判所",
    address: "大阪府大阪市北区西天満2-9-6",
    stampAmount: 6000,
  },
  {
    prefecture: '大阪府',
    areas: ["堺市", "堺市堺区", "堺市中区", "堺市東区", "堺市西区", "堺市南区", "堺市北区", "堺市美原区"],
    name: "堺簡易裁判所",
    address: "大阪府堺市堺区南瓦町2-29",
    stampAmount: 6000,
  },
  {
    prefecture: '大阪府',
    areas: ["岸和田市", "泉大津市", "和泉市", "高石市", "泉北郡"],
    name: "岸和田簡易裁判所",
    address: "大阪府岸和田市今福町1-6-2",
    stampAmount: 4000,
  },
  {
    prefecture: '大阪府',
    areas: ["富田林市", "河内長野市", "大阪狭山市", "南河内郡"],
    name: "富田林簡易裁判所",
    address: "大阪府富田林市本町2-30",
    stampAmount: 4000,
  },
  {
    prefecture: '大阪府',
    areas: ["東大阪市", "八尾市", "柏原市"],
    name: "東大阪簡易裁判所",
    address: "大阪府東大阪市高井田元町2丁目8-34",
    stampAmount: 4000,
  },
  {
    prefecture: '大阪府',
    areas: ["泉佐野市", "貝塚市", "泉南市", "阪南市", "熊取町", "田尻町", "岬町", "泉南郡"],
    name: "泉佐野簡易裁判所",
    address: "大阪府泉佐野市上町1-3-28",
    stampAmount: 3000,
  },
  {
    prefecture: '大阪府',
    areas: ["豊中市"],
    name: "豊中簡易裁判所",
    address: "大阪府豊中市中桜塚1丁目",
    stampAmount: 4000,
  },
  {
    prefecture: '大阪府',
    areas: ["池田市", "箕面市"],
    name: "大阪池田簡易裁判所",
    address: "大阪府池田市城南1丁目3-35",
    stampAmount: 4000,
  },
  {
    prefecture: '大阪府',
    areas: ["羽曳野市", "藤井寺市", "松原市"],
    name: "羽曳野簡易裁判所",
    address: "大阪府羽曳野市誉田4丁目",
    stampAmount: 4000,
  },
  {
    prefecture: '大阪府',
    areas: ["枚方市", "寝屋川市", "交野市", "四條畷市", "大東市"],
    name: "枚方簡易裁判所",
    address: "大阪府枚方市大垣内町2丁目",
    stampAmount: 4000,
  },
  {
    prefecture: '大阪府',
    areas: ["吹田市"],
    name: "吹田簡易裁判所",
    address: "大阪府吹田市垂水町3丁目",
    stampAmount: 4000,
  },
  {
    prefecture: '大阪府',
    areas: ["茨木市", "摂津市", "高槻市", "三島郡"],
    name: "茨木簡易裁判所",
    address: "大阪府茨木市駅前3丁目",
    stampAmount: 4000,
  },
  // ========== 兵庫県 ==========
  {
    prefecture: '兵庫県',
    areas: ["神戸市", "芦屋市", "西宮市", "宝塚市", "伊丹市", "川西市", "三田市", "猪名川町"],
    name: "神戸簡易裁判所",
    address: "兵庫県神戸市中央区橘通2丁目4-3",
    stampAmount: 6000,
  },
  {
    prefecture: '兵庫県',
    areas: ["姫路市", "神崎郡", "揖保郡", "宍粟市"],
    name: "姫路簡易裁判所",
    address: "兵庫県姫路市本町68",
    stampAmount: 4000,
  },
  {
    prefecture: '兵庫県',
    areas: ["尼崎市"],
    name: "尼崎簡易裁判所",
    address: "兵庫県尼崎市七松町1丁目3-1",
    stampAmount: 4000,
  },
  {
    prefecture: '兵庫県',
    areas: ["西脇市", "加東市", "小野市", "加西市", "多可郡"],
    name: "西脇簡易裁判所",
    address: "兵庫県西脇市野村町1丁目180",
    stampAmount: 3000,
  },
  {
    prefecture: '兵庫県',
    areas: ["豊岡市", "朝来市", "養父市", "美方郡"],
    name: "豊岡簡易裁判所",
    address: "兵庫県豊岡市幸町7-11",
    stampAmount: 3000,
  },
  {
    prefecture: '兵庫県',
    areas: ["丹波篠山市", "丹波市"],
    name: "柏原簡易裁判所",
    address: "兵庫県丹波市柏原町柏原683",
    stampAmount: 3000,
  },
  {
    prefecture: '兵庫県',
    areas: ["たつの市", "赤穂市", "相生市", "赤穂郡", "佐用郡"],
    name: "龍野簡易裁判所",
    address: "兵庫県たつの市龍野町富永117-1",
    stampAmount: 3000,
  },
  {
    prefecture: '兵庫県',
    areas: ["洲本市", "南あわじ市", "淡路市"],
    name: "洲本簡易裁判所",
    address: "兵庫県洲本市本町3丁目4-12",
    stampAmount: 3000,
  },
  // ========== 奈良県 ==========
  {
    prefecture: '奈良県',
    areas: ["奈良市", "大和郡山市", "天理市", "生駒市", "山辺郡", "生駒郡", "宇陀郡", "宇陀市"],
    name: "奈良簡易裁判所",
    address: "奈良県奈良市登大路町36-1",
    stampAmount: 4000,
  },
  {
    prefecture: '奈良県',
    areas: ["大和高田市", "橿原市", "桜井市", "磯城郡", "高市郡"],
    name: "大和高田簡易裁判所",
    address: "奈良県大和高田市神楽2丁目9-21",
    stampAmount: 3000,
  },
  {
    prefecture: '奈良県',
    areas: ["五條市", "吉野郡", "御所市", "葛城市"],
    name: "五條簡易裁判所",
    address: "奈良県五條市本町1丁目1-49",
    stampAmount: 3000,
  },
  {
    prefecture: '奈良県',
    areas: ["橋本市", "伊都郡"],
    name: "橋本簡易裁判所",
    address: "和歌山県橋本市古佐田1丁目1-11",
    stampAmount: 3000,
  },
  // ========== 和歌山県 ==========
  {
    prefecture: '和歌山県',
    areas: ["和歌山市", "海南市", "岩出市", "紀の川市", "海草郡"],
    name: "和歌山簡易裁判所",
    address: "和歌山県和歌山市二番丁1",
    stampAmount: 4000,
  },
  {
    prefecture: '和歌山県',
    areas: ["田辺市", "西牟婁郡", "日高郡"],
    name: "田辺簡易裁判所",
    address: "和歌山県田辺市高雄1丁目23-1",
    stampAmount: 3000,
  },
  {
    prefecture: '和歌山県',
    areas: ["新宮市", "東牟婁郡"],
    name: "新宮簡易裁判所",
    address: "和歌山県新宮市春日1丁目1-1",
    stampAmount: 3000,
  },
  {
    prefecture: '和歌山県',
    areas: ["御坊市", "日高郡", "有田郡", "有田市"],
    name: "御坊簡易裁判所",
    address: "和歌山県御坊市塩屋町南塩屋36",
    stampAmount: 3000,
  },
  // ========== 鳥取県 ==========
  {
    prefecture: '鳥取県',
    areas: ["鳥取市", "岩美郡", "八頭郡"],
    name: "鳥取簡易裁判所",
    address: "鳥取県鳥取市東町2丁目315",
    stampAmount: 3000,
  },
  {
    prefecture: '鳥取県',
    areas: ["倉吉市", "東伯郡"],
    name: "倉吉簡易裁判所",
    address: "鳥取県倉吉市仲ノ町3549",
    stampAmount: 3000,
  },
  {
    prefecture: '鳥取県',
    areas: ["米子市", "境港市", "西伯郡", "日野郡"],
    name: "米子簡易裁判所",
    address: "鳥取県米子市法勝寺町1",
    stampAmount: 3000,
  },
  // ========== 島根県 ==========
  {
    prefecture: '島根県',
    areas: ["松江市", "安来市", "仁多郡", "隠岐郡"],
    name: "松江簡易裁判所",
    address: "島根県松江市殿町1",
    stampAmount: 3000,
  },
  {
    prefecture: '島根県',
    areas: ["浜田市", "江津市", "邑智郡"],
    name: "浜田簡易裁判所",
    address: "島根県浜田市三原町1組",
    stampAmount: 3000,
  },
  {
    prefecture: '島根県',
    areas: ["出雲市", "雲南市", "飯石郡", "仁多郡奥出雲町"],
    name: "出雲簡易裁判所",
    address: "島根県出雲市今市町70",
    stampAmount: 3000,
  },
  {
    prefecture: '島根県',
    areas: ["益田市", "鹿足郡"],
    name: "益田簡易裁判所",
    address: "島根県益田市幸町6-1",
    stampAmount: 3000,
  },
  {
    prefecture: '島根県',
    areas: ["大田市", "邑智郡大和村"],
    name: "大田簡易裁判所",
    address: "島根県大田市大田町大田ハ1",
    stampAmount: 3000,
  },
  // ========== 岡山県 ==========
  {
    prefecture: '岡山県',
    areas: ["岡山市", "玉野市", "和気郡", "赤磐市", "都窪郡", "総社市"],
    name: "岡山簡易裁判所",
    address: "岡山県岡山市北区南方1丁目8-42",
    stampAmount: 4000,
  },
  {
    prefecture: '岡山県',
    areas: ["倉敷市", "浅口市", "浅口郡", "小田郡矢掛町", "早島町", "里庄町"],
    name: "倉敷簡易裁判所",
    address: "岡山県倉敷市幸町3-33",
    stampAmount: 4000,
  },
  {
    prefecture: '岡山県',
    areas: ["津山市", "真庭市", "美作市", "勝田郡", "苫田郡", "英田郡", "久米郡"],
    name: "津山簡易裁判所",
    address: "岡山県津山市山北520",
    stampAmount: 3000,
  },
  {
    prefecture: '岡山県',
    areas: ["笠岡市", "井原市", "小田郡", "高梁市", "新見市"],
    name: "笠岡簡易裁判所",
    address: "岡山県笠岡市中央町1-25",
    stampAmount: 3000,
  },
  {
    prefecture: '岡山県',
    areas: ["備前市", "瀬戸内市"],
    name: "備前簡易裁判所",
    address: "岡山県備前市東片上1丁目",
    stampAmount: 3000,
  },
  // ========== 広島県 ==========
  {
    prefecture: '広島県',
    areas: ["広島市", "廿日市市", "大竹市", "山県郡", "安芸郡", "安芸高田市"],
    name: "広島簡易裁判所",
    address: "広島県広島市中区上八丁堀2-43",
    stampAmount: 6000,
  },
  {
    prefecture: '広島県',
    areas: ["呉市", "江田島市"],
    name: "呉簡易裁判所",
    address: "広島県呉市中央4丁目1-6",
    stampAmount: 4000,
  },
  {
    prefecture: '広島県',
    areas: ["尾道市", "三原市", "世羅郡"],
    name: "尾道簡易裁判所",
    address: "広島県尾道市西御所町7-1",
    stampAmount: 3000,
  },
  {
    prefecture: '広島県',
    areas: ["福山市", "府中市", "神石郡"],
    name: "福山簡易裁判所",
    address: "広島県福山市三吉町1丁目7-1",
    stampAmount: 4000,
  },
  {
    prefecture: '広島県',
    areas: ["三次市", "庄原市", "双三郡"],
    name: "三次簡易裁判所",
    address: "広島県三次市十日市東4丁目6-1",
    stampAmount: 3000,
  },
  {
    prefecture: '広島県',
    areas: ["東広島市", "竹原市", "豊田郡"],
    name: "安芸簡易裁判所",
    address: "広島県東広島市西条町御薗宇6226",
    stampAmount: 3000,
  },
  // ========== 山口県 ==========
  {
    prefecture: '山口県',
    areas: ["山口市", "防府市", "萩市", "阿武郡"],
    name: "山口簡易裁判所",
    address: "山口県山口市中河原町6-16",
    stampAmount: 4000,
  },
  {
    prefecture: '山口県',
    areas: ["下関市"],
    name: "下関簡易裁判所",
    address: "山口県下関市東本町2丁目1-26",
    stampAmount: 4000,
  },
  {
    prefecture: '山口県',
    areas: ["宇部市", "山陽小野田市", "美祢市"],
    name: "宇部簡易裁判所",
    address: "山口県宇部市常盤町1丁目7-1",
    stampAmount: 3000,
  },
  {
    prefecture: '山口県',
    areas: ["周南市", "光市", "下松市", "熊毛郡"],
    name: "徳山簡易裁判所",
    address: "山口県周南市孤松園1丁目5-9",
    stampAmount: 3000,
  },
  {
    prefecture: '山口県',
    areas: ["岩国市", "柳井市", "大島郡", "玖珂郡"],
    name: "岩国簡易裁判所",
    address: "山口県岩国市三笠町1丁目1-1",
    stampAmount: 3000,
  },
  // ========== 徳島県 ==========
  {
    prefecture: '徳島県',
    areas: ["徳島市", "鳴門市", "阿南市", "小松島市", "吉野川市", "板野郡", "名東郡", "名西郡", "那賀郡"],
    name: "徳島簡易裁判所",
    address: "徳島県徳島市徳島町城内6-6",
    stampAmount: 4000,
  },
  {
    prefecture: '徳島県',
    areas: ["美馬市", "美馬郡", "三好市", "三好郡"],
    name: "脇町簡易裁判所",
    address: "徳島県美馬市脇町字拝原1431",
    stampAmount: 3000,
  },
  {
    prefecture: '徳島県',
    areas: ["海部郡", "海陽町", "牟岐町", "美波町", "阿南市椿町"],
    name: "牟岐簡易裁判所",
    address: "徳島県海部郡牟岐町大字中村字本村116",
    stampAmount: 3000,
  },
  // ========== 香川県 ==========
  {
    prefecture: '香川県',
    areas: ["高松市", "さぬき市", "東かがわ市", "木田郡", "小豆郡", "香川郡"],
    name: "高松簡易裁判所",
    address: "香川県高松市丸の内1-36",
    stampAmount: 4000,
  },
  {
    prefecture: '香川県',
    areas: ["丸亀市", "坂出市", "善通寺市", "仲多度郡", "綾歌郡"],
    name: "丸亀簡易裁判所",
    address: "香川県丸亀市大手町2丁目4-1",
    stampAmount: 3000,
  },
  {
    prefecture: '香川県',
    areas: ["観音寺市", "三豊市"],
    name: "観音寺簡易裁判所",
    address: "香川県観音寺市観音寺町甲2730",
    stampAmount: 3000,
  },
  // ========== 愛媛県 ==========
  {
    prefecture: '愛媛県',
    areas: ["松山市", "伊予市", "東温市", "伊予郡"],
    name: "松山簡易裁判所",
    address: "愛媛県松山市一番町4丁目4-1",
    stampAmount: 4000,
  },
  {
    prefecture: '愛媛県',
    areas: ["宇和島市", "北宇和郡", "南宇和郡", "愛南町"],
    name: "宇和島簡易裁判所",
    address: "愛媛県宇和島市丸之内2丁目4-1",
    stampAmount: 3000,
  },
  {
    prefecture: '愛媛県',
    areas: ["今治市", "越智郡"],
    name: "今治簡易裁判所",
    address: "愛媛県今治市旭町1丁目3-1",
    stampAmount: 3000,
  },
  {
    prefecture: '愛媛県',
    areas: ["西条市", "新居浜市"],
    name: "西条簡易裁判所",
    address: "愛媛県西条市明屋敷164",
    stampAmount: 3000,
  },
  {
    prefecture: '愛媛県',
    areas: ["八幡浜市", "西宇和郡", "大洲市", "喜多郡"],
    name: "八幡浜簡易裁判所",
    address: "愛媛県八幡浜市北浜1丁目3-37",
    stampAmount: 3000,
  },
  // ========== 高知県 ==========
  {
    prefecture: '高知県',
    areas: ["高知市", "南国市", "香美市", "香南市", "土佐市", "長岡郡", "吾川郡", "土佐郡"],
    name: "高知簡易裁判所",
    address: "高知県高知市丸ノ内2丁目4-1",
    stampAmount: 4000,
  },
  {
    prefecture: '高知県',
    areas: ["安芸市", "室戸市", "安芸郡"],
    name: "安芸簡易裁判所",
    address: "高知県安芸市矢ノ丸1丁目4-1",
    stampAmount: 3000,
  },
  {
    prefecture: '高知県',
    areas: ["須崎市", "高岡郡"],
    name: "須崎簡易裁判所",
    address: "高知県須崎市栄町1丁目1-1",
    stampAmount: 3000,
  },
  {
    prefecture: '高知県',
    areas: ["四万十市", "幡多郡四万十町", "幡多郡黒潮町"],
    name: "中村簡易裁判所",
    address: "高知県四万十市中村大橋通2丁目2-1",
    stampAmount: 3000,
  },
  {
    prefecture: '高知県',
    areas: ["宿毛市", "土佐清水市", "幡多郡大月町", "幡多郡三原村"],
    name: "宿毛簡易裁判所",
    address: "高知県宿毛市桜町5-10",
    stampAmount: 3000,
  },
  // ========== 福岡県 ==========
  {
    prefecture: '福岡県',
    areas: ["福岡市", "春日市", "大野城市", "筑紫野市", "太宰府市", "古賀市", "糟屋郡", "筑紫郡", "宗像市", "福津市"],
    name: "福岡簡易裁判所",
    address: "福岡県福岡市中央区城内1-1",
    stampAmount: 6000,
  },
  {
    prefecture: '福岡県',
    areas: ["北九州市", "遠賀郡", "中間市", "芦屋町"],
    name: "小倉簡易裁判所",
    address: "福岡県北九州市小倉北区城内1-1",
    stampAmount: 6000,
  },
  {
    prefecture: '福岡県',
    areas: ["飯塚市", "嘉麻市", "田川市", "田川郡"],
    name: "飯塚簡易裁判所",
    address: "福岡県飯塚市新立岩8-1",
    stampAmount: 3000,
  },
  {
    prefecture: '福岡県',
    areas: ["行橋市", "豊前市", "京都郡", "築上郡"],
    name: "行橋簡易裁判所",
    address: "福岡県行橋市中央1丁目12-35",
    stampAmount: 3000,
  },
  {
    prefecture: '福岡県',
    areas: ["直方市", "宮若市", "鞍手郡"],
    name: "直方簡易裁判所",
    address: "福岡県直方市山部424-1",
    stampAmount: 3000,
  },
  {
    prefecture: '福岡県',
    areas: ["八女市", "筑後市", "八女郡"],
    name: "八女簡易裁判所",
    address: "福岡県八女市本町2丁目1-1",
    stampAmount: 3000,
  },
  {
    prefecture: '福岡県',
    areas: ["柳川市", "みやま市", "大川市", "大牟田市", "三池郡"],
    name: "柳川簡易裁判所",
    address: "福岡県柳川市本町58",
    stampAmount: 3000,
  },
  {
    prefecture: '福岡県',
    areas: ["久留米市", "うきは市", "朝倉市", "朝倉郡", "三井郡"],
    name: "久留米簡易裁判所",
    address: "福岡県久留米市城南町15-40",
    stampAmount: 4000,
  },
  // ========== 佐賀県 ==========
  {
    prefecture: '佐賀県',
    areas: ["佐賀市", "神埼市", "神埼郡", "小城市", "多久市"],
    name: "佐賀簡易裁判所",
    address: "佐賀県佐賀市城内1丁目1-45",
    stampAmount: 4000,
  },
  {
    prefecture: '佐賀県',
    areas: ["唐津市", "東松浦郡", "伊万里市", "西松浦郡"],
    name: "唐津簡易裁判所",
    address: "佐賀県唐津市西城内12-38",
    stampAmount: 3000,
  },
  {
    prefecture: '佐賀県',
    areas: ["武雄市", "鹿島市", "嬉野市", "杵島郡", "藤津郡"],
    name: "武雄簡易裁判所",
    address: "佐賀県武雄市武雄町大字武雄5304-2",
    stampAmount: 3000,
  },
  // ========== 長崎県 ==========
  {
    prefecture: '長崎県',
    areas: ["長崎市", "西彼杵郡", "時津町", "長与町", "大村市", "諫早市"],
    name: "長崎簡易裁判所",
    address: "長崎県長崎市万才町8-16",
    stampAmount: 4000,
  },
  {
    prefecture: '長崎県',
    areas: ["佐世保市", "東彼杵郡", "北松浦郡", "平戸市", "松浦市"],
    name: "佐世保簡易裁判所",
    address: "長崎県佐世保市島地町11-1",
    stampAmount: 4000,
  },
  {
    prefecture: '長崎県',
    areas: ["島原市", "雲仙市", "南島原市", "南高来郡"],
    name: "島原簡易裁判所",
    address: "長崎県島原市城内1丁目1205",
    stampAmount: 3000,
  },
  {
    prefecture: '長崎県',
    areas: ["対馬市"],
    name: "厳原簡易裁判所",
    address: "長崎県対馬市厳原町国分1441",
    stampAmount: 3000,
  },
  {
    prefecture: '長崎県',
    areas: ["五島市", "南松浦郡"],
    name: "福江簡易裁判所",
    address: "長崎県五島市栄町1-3",
    stampAmount: 3000,
  },
  {
    prefecture: '長崎県',
    areas: ["壱岐市"],
    name: "郷ノ浦簡易裁判所",
    address: "長崎県壱岐市郷ノ浦町本村触616",
    stampAmount: 3000,
  },
  // ========== 熊本県 ==========
  {
    prefecture: '熊本県',
    areas: ["熊本市", "宇城市", "宇土市", "上益城郡", "菊池市", "合志市", "菊池郡", "阿蘇市", "阿蘇郡"],
    name: "熊本簡易裁判所",
    address: "熊本県熊本市中央区京町1丁目12-36",
    stampAmount: 4000,
  },
  {
    prefecture: '熊本県',
    areas: ["八代市", "氷川郡", "葦北郡"],
    name: "八代簡易裁判所",
    address: "熊本県八代市松江城町7-18",
    stampAmount: 3000,
  },
  {
    prefecture: '熊本県',
    areas: ["人吉市", "球磨郡"],
    name: "人吉簡易裁判所",
    address: "熊本県人吉市麓町16-3",
    stampAmount: 3000,
  },
  {
    prefecture: '熊本県',
    areas: ["山鹿市"],
    name: "山鹿簡易裁判所",
    address: "熊本県山鹿市山鹿987-2",
    stampAmount: 3000,
  },
  {
    prefecture: '熊本県',
    areas: ["玉名市", "荒尾市", "玉名郡"],
    name: "玉名簡易裁判所",
    address: "熊本県玉名市繁根木187",
    stampAmount: 3000,
  },
  {
    prefecture: '熊本県',
    areas: ["天草市", "上天草市", "天草郡"],
    name: "本渡簡易裁判所",
    address: "熊本県天草市中央新町18-1",
    stampAmount: 3000,
  },
  // ========== 大分県 ==========
  {
    prefecture: '大分県',
    areas: ["大分市", "由布市", "臼杵市", "津久見市"],
    name: "大分簡易裁判所",
    address: "大分県大分市荷揚町7-5",
    stampAmount: 4000,
  },
  {
    prefecture: '大分県',
    areas: ["別府市", "杵築市", "国東市", "東国東郡", "速見郡"],
    name: "別府簡易裁判所",
    address: "大分県別府市上野口町2-30",
    stampAmount: 3000,
  },
  {
    prefecture: '大分県',
    areas: ["中津市", "豊後高田市", "宇佐市", "下毛郡"],
    name: "中津簡易裁判所",
    address: "大分県中津市丸山2丁目6-24",
    stampAmount: 3000,
  },
  {
    prefecture: '大分県',
    areas: ["佐伯市", "南海部郡"],
    name: "佐伯簡易裁判所",
    address: "大分県佐伯市城下東町1-1",
    stampAmount: 3000,
  },
  {
    prefecture: '大分県',
    areas: ["日田市", "玖珠郡"],
    name: "日田簡易裁判所",
    address: "大分県日田市城町2-4",
    stampAmount: 3000,
  },
  {
    prefecture: '大分県',
    areas: ["竹田市", "豊後大野市", "直入郡"],
    name: "竹田簡易裁判所",
    address: "大分県竹田市大字竹田字殿町1",
    stampAmount: 3000,
  },
  // ========== 宮崎県 ==========
  {
    prefecture: '宮崎県',
    areas: ["宮崎市", "東諸県郡", "宮崎郡", "西都市", "児湯郡"],
    name: "宮崎簡易裁判所",
    address: "宮崎県宮崎市別府町1-1",
    stampAmount: 4000,
  },
  {
    prefecture: '宮崎県',
    areas: ["都城市", "北諸県郡", "小林市", "えびの市", "西諸県郡"],
    name: "都城簡易裁判所",
    address: "宮崎県都城市早鈴町17-7",
    stampAmount: 3000,
  },
  {
    prefecture: '宮崎県',
    areas: ["延岡市", "東臼杵郡"],
    name: "延岡簡易裁判所",
    address: "宮崎県延岡市本小路68-1",
    stampAmount: 3000,
  },
  {
    prefecture: '宮崎県',
    areas: ["日向市", "門川町"],
    name: "日向簡易裁判所",
    address: "宮崎県日向市本町1-7",
    stampAmount: 3000,
  },
  {
    prefecture: '宮崎県',
    areas: ["高千穂町", "西臼杵郡"],
    name: "高千穂簡易裁判所",
    address: "宮崎県西臼杵郡高千穂町大字三田井1283",
    stampAmount: 3000,
  },
  // ========== 鹿児島県 ==========
  {
    prefecture: '鹿児島県',
    areas: ["鹿児島市", "日置市", "いちき串木野市"],
    name: "鹿児島簡易裁判所",
    address: "鹿児島県鹿児島市鷹師1丁目1-1",
    stampAmount: 4000,
  },
  {
    prefecture: '鹿児島県',
    areas: ["鹿屋市", "垂水市", "肝属郡", "曽於市", "志布志市"],
    name: "鹿屋簡易裁判所",
    address: "鹿児島県鹿屋市打馬2丁目16-13",
    stampAmount: 3000,
  },
  {
    prefecture: '鹿児島県',
    areas: ["霧島市", "姶良市", "姶良郡", "伊佐市"],
    name: "国分簡易裁判所",
    address: "鹿児島県霧島市国分中央3丁目45-1",
    stampAmount: 3000,
  },
  {
    prefecture: '鹿児島県',
    areas: ["南さつま市", "枕崎市", "川辺郡"],
    name: "加世田簡易裁判所",
    address: "鹿児島県南さつま市加世田川畑2231",
    stampAmount: 3000,
  },
  {
    prefecture: '鹿児島県',
    areas: ["出水市", "阿久根市", "薩摩郡"],
    name: "出水簡易裁判所",
    address: "鹿児島県出水市緑町11-34",
    stampAmount: 3000,
  },
  {
    prefecture: '鹿児島県',
    areas: ["薩摩川内市", "薩摩郡"],
    name: "川内簡易裁判所",
    address: "鹿児島県薩摩川内市隈之城町222-1",
    stampAmount: 3000,
  },
  {
    prefecture: '鹿児島県',
    areas: ["西之表市", "熊毛郡"],
    name: "西之表簡易裁判所",
    address: "鹿児島県西之表市西之表7600",
    stampAmount: 3000,
  },
  {
    prefecture: '鹿児島県',
    areas: ["奄美市", "大島郡"],
    name: "名瀬簡易裁判所",
    address: "鹿児島県奄美市名瀬長浜町1-1",
    stampAmount: 3000,
  },
  // ========== 沖縄県 ==========
  {
    prefecture: '沖縄県',
    areas: ["那覇市", "豊見城市", "糸満市", "南城市", "八重瀬町", "与那原町", "南風原町", "浦添市", "宜野湾市"],
    name: "那覇簡易裁判所",
    address: "沖縄県那覇市泉崎1丁目12-1",
    stampAmount: 4000,
  },
  {
    prefecture: '沖縄県',
    areas: ["名護市", "国頭郡", "今帰仁村", "本部町"],
    name: "名護簡易裁判所",
    address: "沖縄県名護市港2丁目1-14",
    stampAmount: 3000,
  },
  {
    prefecture: '沖縄県',
    areas: ["沖縄市", "うるま市", "読谷村", "嘉手納町", "北谷町", "北中城村", "中城村", "西原町", "恩納村", "金武町", "宜野座村"],
    name: "沖縄簡易裁判所",
    address: "沖縄県沖縄市知花6丁目6-1",
    stampAmount: 3000,
  },
  {
    prefecture: '沖縄県',
    areas: ["宮古島市", "多良間村"],
    name: "平良簡易裁判所",
    address: "沖縄県宮古島市平良字西里1-1",
    stampAmount: 3000,
  },
  {
    prefecture: '沖縄県',
    areas: ["石垣市", "竹富町", "与那国町"],
    name: "石垣簡易裁判所",
    address: "沖縄県石垣市美崎町11-3",
    stampAmount: 3000,
  },
]

/**
 * 都道府県と市区町村から管轄簡易裁判所を検索する
 * マッチングロジック（4段階）:
 * 1. 完全一致
 * 2. 前方一致（例:「横浜市西区」→「横浜市」にマッチ）
 * 3. 逆前方一致（例:「豊岡」→「豊岡市」にマッチ）
 * 4. 都道府県フォールバック（都道府県内の最初のエントリを返す）
 */
export function findCourt(prefecture: string, city: string): Court | null {
  const prefectureEntries = courtData.filter(e => e.prefecture === prefecture)
  if (prefectureEntries.length === 0) return null

  // Step 1: 完全一致
  let entry = prefectureEntries.find(e => e.areas.some(area => area === city))

  // Step 2: 前方一致（city が area で始まる: 例「横浜市西区」→「横浜市」）
  if (!entry) {
    entry = prefectureEntries.find(e => e.areas.some(area => city.startsWith(area)))
  }

  // Step 3: 逆前方一致（area が city で始まる: 例「豊岡」→「豊岡市」）
  if (!entry) {
    entry = prefectureEntries.find(e => e.areas.some(area => area.startsWith(city)))
  }

  // Step 4: 都道府県フォールバック（都道府県内の最初のエントリ）
  if (!entry) {
    entry = prefectureEntries[0]
  }

  if (!entry) return null

  return {
    name: entry.name,
    address: entry.address,
    stampAmount: entry.stampAmount,
  }
}

/**
 * 対応している都道府県の一覧を返す
 */
export const supportedPrefectures = [
  '北海道', '青森県', '岩手県', '宮城県', '秋田県', '山形県', '福島県',
  '茨城県', '栃木県', '群馬県', '埼玉県', '千葉県', '東京都', '神奈川県',
  '新潟県', '富山県', '石川県', '福井県', '山梨県', '長野県', '岐阜県',
  '静岡県', '愛知県', '三重県', '滋賀県', '京都府', '大阪府', '兵庫県',
  '奈良県', '和歌山県', '鳥取県', '島根県', '岡山県', '広島県', '山口県',
  '徳島県', '香川県', '愛媛県', '高知県', '福岡県', '佐賀県', '長崎県',
  '熊本県', '大分県', '宮崎県', '鹿児島県', '沖縄県',
]

export { courtData }